export const PAYMENT_COPY = {
  header: {
    title: 'Payment Release & Settlement Console',
    subtitle: 'Treasury workbench for batching verified invoices, ISO 20022 Pain.001 dispatch, and bank settlement.',
    createBatchCTA: 'Create Payment Batch',
  },
  tabs: {
    dueInvoices: 'Pending Settlement Invoices',
    batches:     'Payment Batches & XML Archive',
  },
  kpi: {
    dueExposure: 'Approved Due Exposure',
    dueExposureSub: 'Cleared 3-way match invoices ready for payment',
    dueCount: 'Invoices Ready for Batch',
    dueCountSub: 'Awaiting treasury batch grouping',
    activeBatches: 'Batches Awaiting Dispatch',
    activeBatchesSub: 'Draft settlement files requiring dual approval',
    dispatchedVolume: 'Settled / Dispatched Volume',
    dispatchedVolumeSub: 'Transferred via ISO 20022 / EFT rails',
  },
  table: {
    colSelect: 'Select',
    colInvoice: 'Invoice # (ETTN)',
    colVendor: 'Payee Supplier',
    colIban: 'Settlement IBAN',
    colEntity: 'Legal Entity',
    colDate: 'Invoice Date',
    colAmount: 'Payable Amount',
    colMatch: 'Match Status',
    searchPlaceholder: 'Search invoice #, supplier name, IBAN, or entity...',
    emptyDueTitle: 'No Pending Invoices for Settlement',
    emptyDueDesc: 'All approved invoices have been batched and dispatched for payment.',
    emptyBatchesTitle: 'No Payment Batches Found',
    emptyBatchesDesc: 'No payment batches have been compiled yet.',
    colBatchNo: 'Batch Number',
    colMethod: 'Payment Rail',
    colItemCount: 'Invoices Count',
    colTotal: 'Batch Total',
    colCreatedBy: 'Compiled By',
    colApprovedBy: 'Authorized By',
    colStatus: 'Batch Status',
    colCreatedDate: 'Created Date',
    inspectBatchAction: 'Inspect Batch',
  },
  modal: {
    title: 'Compile Treasury Payment Batch',
    description: 'Group selected verified invoices into an ISO 20022 Pain.001 / EFT settlement package.',
    selectEntity: 'Originating Legal Entity & Bank Account',
    paymentMethod: 'Settlement Rail / Format',
    methodIso: 'ISO 20022 Pain.001.001.03 (SEPA / Corporate Banking)',
    methodEft: 'Domestic Turkish EFT / FAST Bank Transfer',
    methodSwift: 'SWIFT MT103 Cross-Border Wire Transfer',
    selectedSummary: 'Selected Invoices for Settlement',
    totalPayable: 'Total Batch Net Payable',
    submitCTA: 'Generate Settlement Batch',
    submittingCTA: 'Compiling ISO 20022 XML...',
  },
  drawer: {
    title: 'Payment Batch Inspector',
    subtitle: 'ISO 20022 XML Dispatch & Authorization Console',
    sectionSummary: 'Batch Commercial Summary',
    sectionItems: 'Included Invoices & Payee Accounts',
    sectionXml: 'ISO 20022 pain.001.001.03 XML Payload',
    approveCTA: 'Authorize & Dispatch to Bank',
    cancelCTA: 'Cancel Batch',
    doubleConfirmTitle: 'Four-Eyes Principle: Authorize Final Bank Dispatch',
    doubleConfirmDesc: 'This will initiate automated bank transfers to all listed suppliers. This action cannot be reversed.',
    copyXml: 'Copy XML Payload',
    xmlCopied: 'Copied to clipboard!',
  },
} as const
