/**
 * All copy and label constants for the Purchase Requisition (PR) module.
 * Zero hardcode policy — everything is defined here in English.
 */
export const REQUISITION_COPY = {
  list: {
    pageTitle:          'Purchase Requisitions',
    pageSubtitle:       'Create, track, and manage employee purchase requests across legal entities.',
    createCTA:          '+ New Purchase Request',
    searchPlaceholder:  'Search by PR number, title, or requester...',
    filterStatus:       'All Statuses',
    filterCostCenter:   'All Cost Centers',
    colPrNumber:        'PR Number',
    colTitle:           'Title / Justification',
    colCostCenter:      'Cost Center',
    colRequester:       'Requester',
    colAmount:          'Total Estimated Amount',
    colStatus:          'Status',
    colDate:            'Created Date',
    colActions:         'Actions',
    viewDetail:         'View Details',
    cancelPR:           'Cancel Request',
    confirmCancelTitle: 'Cancel Purchase Request',
    confirmCancelDesc:  'Are you sure you want to cancel this requisition? This will release reserved budget allocations and cancel all pending approval steps.',
    emptyTitle:         'No Purchase Requests Found',
    emptyDesc:          'No requisitions match your filter criteria. Create a new purchase request to begin.',
  },
  create: {
    pageTitle:          'Create Purchase Request',
    pageSubtitle:       'Submit a new requisition for budget validation and multi-tier approval routing.',
    backToList:         'Back to Requisitions',
    sectionHeader:      '1. Organizational Context & Scope',
    sectionLineItems:   '2. Line Items Breakdown',
    sectionBudget:      '3. Real-Time Budget Simulation',
    legalEntityLabel:   'Legal Entity',
    costCenterLabel:    'Cost Center',
    facilityLabel:      'Delivery Facility',
    titleLabel:         'Requisition Title',
    titlePlaceholder:   'e.g., Q3 Server Hardware Refresh or Office Ergonomics',
    justificationLabel: 'Business Justification',
    justificationPlaceholder: 'Explain the business necessity and expected operational benefit...',
    currencyLabel:      'Currency',
    addLineItemCTA:     '+ Add Line Item',
    colItemDesc:        'Item Description',
    colCategory:        'Category',
    colQty:             'Quantity',
    colUOM:             'UOM',
    colUnitPrice:       'Unit Price',
    colLineTotal:       'Estimated Line Total',
    totalLabel:         'Total Estimated Requisition Amount:',
    cancelButton:       'Discard',
    submitButton:       'Submit Requisition for Approval',
    submitting:         'Validating & Submitting...',
  },
  budgetCheck: {
    title:              'Cost Center Budget Availability Check',
    allocatedLabel:     'Total Allocated:',
    committedLabel:     'Spent + Reserved:',
    thisPRLabel:        'This Request:',
    projectedLabel:     'Projected Utilization:',
    availableLabel:     'Remaining Available:',
    hardStopAlert:      'Warning: This requisition exceeds the available budget limit. Submission will be rejected by the budget enforcement policy.',
    warningAlert:       'Notice: This request will bring budget utilization above the 80% warning threshold.',
    noPoolAlert:        'No active budget pool found for the selected cost center and fiscal year. Please contact your finance team.',
  },
  drawer: {
    title:              'Requisition Details',
    subtitle:           'Inspect line items, delivery details, and DoA approval status.',
    sectionScope:       'Requisition Overview',
    sectionItems:       'Line Items',
    sectionApproval:    'Approval Chain & Audit Stepper',
    requesterLabel:     'Requested By:',
    entityLabel:        'Legal Entity:',
    costCenterLabel:    'Cost Center:',
    facilityLabel:      'Delivery Destination:',
    justificationLabel: 'Business Justification:',
    rejectionLabel:     'Rejection Reason:',
    stepLabel:          'Step',
    approverLabel:      'Approver:',
    statusPending:      'Pending Review',
    statusApproved:     'Approved',
    statusRejected:     'Rejected',
    statusBypassed:     'Bypassed',
    cancelAction:       'Cancel Requisition',
    closeDrawer:        'Close',
  },
  uomOptions: [
    { value: 'PIECE', label: 'Piece (Pcs)' },
    { value: 'BOX', label: 'Box' },
    { value: 'HOUR', label: 'Hour (Hrs)' },
    { value: 'SET', label: 'Set' },
    { value: 'KG', label: 'Kilogram (Kg)' },
    { value: 'METER', label: 'Meter (m)' },
  ],
  categoryOptions: [
    { value: 'IT_HARDWARE', label: 'IT Hardware & Infrastructure' },
    { value: 'SOFTWARE_LICENSE', label: 'Software Licenses & Cloud' },
    { value: 'OFFICE_SUPPLIES', label: 'Office Supplies & Equipment' },
    { value: 'CONSULTING_SERVICES', label: 'Consulting & Professional Services' },
    { value: 'FACILITY_MAINTENANCE', label: 'Facility Maintenance & Utilities' },
    { value: 'MARKETING_ADVERTISING', label: 'Marketing & Advertising' },
  ],
} as const
