export const ORG_COPY = {
  header: {
    title: 'Enterprise Organization & Governance',
    subtitle: 'Manage legal entities, cost center department trees, logistics facilities, user RBAC, and DoA signing thresholds.',
  },
  tabs: {
    legalEntities: 'Legal Entities',
    costCenters:   'Cost Centers',
    facilities:    'Logistics Facilities',
    users:         'User Directory & Invites',
    doaMatrix:     'DoA Authority Matrix',
  },
  kpi: {
    entities: 'Legal Entities',
    entitiesSub: 'Active operating subsidiaries',
    costCenters: 'Cost Centers',
    costCentersSub: 'Department budget units',
    facilities: 'Logistics Facilities',
    facilitiesSub: 'Receiving docks & sites',
    users: 'Active Users',
    usersSub: 'Corporate accounts & roles',
    doaTiers: 'DoA Signing Limits',
    doaTiersSub: 'Configured delegation tiers',
  },
  legalEntity: {
    addCTA: 'Add Legal Entity',
    code: 'Company Code',
    name: 'Entity Name',
    taxNumber: 'Tax ID / VKN',
    taxOffice: 'Tax Office',
    currency: 'Base Currency',
    country: 'Country',
    status: 'Status',
    editAction: 'Edit Entity',
    emptyTitle: 'No Legal Entities Configured',
    emptyDesc: 'Add your primary corporate subsidiary or operating company to begin.',
  },
  costCenter: {
    addCTA: 'Add Cost Center',
    code: 'Cost Center Code',
    name: 'Department / Unit Name',
    entity: 'Legal Entity',
    manager: 'Department Manager',
    status: 'Status',
    editAction: 'Edit Cost Center',
    emptyTitle: 'No Cost Centers Found',
    emptyDesc: 'Cost centers allocate budgets and route approval chains to department managers.',
  },
  facility: {
    addCTA: 'Add Logistics Facility',
    code: 'Facility Code',
    name: 'Facility Name',
    type: 'Facility Type',
    address: 'Shipping Address',
    contact: 'Dock Contact',
    status: 'Status',
    editAction: 'Edit Facility',
    emptyTitle: 'No Facilities Found',
    emptyDesc: 'Logistics facilities designate physical receiving docks and warehouse destinations.',
  },
  user: {
    inviteCTA: 'Invite Sub-Account',
    linkCTA: 'Generate Requisitioner Passkey',
    name: 'User Name',
    email: 'Work Email',
    roles: 'Corporate Roles',
    jobTitle: 'Job Title',
    status: 'Status',
    editRolesAction: 'Manage Roles & Entities',
    emptyTitle: 'No Enterprise Users Found',
    emptyDesc: 'Invite corporate team members to assign approval chains and requisition rights.',
  },
  doa: {
    addCTA: 'Configure DoA Limit',
    user: 'Approver Name',
    entity: 'Legal Entity Scope',
    costCenter: 'Cost Center Scope',
    level: 'Approval Level',
    maxAmount: 'Authorized Ceiling',
    currency: 'Currency',
    status: 'Status',
    emptyTitle: 'No Authority Limits Configured',
    emptyDesc: 'Configure monetary signing thresholds to enforce automated multi-tier approval chains.',
  },
} as const
