package com.enterprise.spendsync.notification.internal.domain;

public enum NotificationEventType {
    PR_APPROVAL_REQUESTED,
    REQUISITION_APPROVED,
    REQUISITION_REJECTED,
    PURCHASE_ORDER_ISSUED,
    PURCHASE_ORDER_CANCELLED,
    GOODS_RECEIVED,
    INVOICE_MATCH_SUCCESS,
    INVOICE_MATCH_FAILED,
    PAYMENT_DISPATCHED,
    BUDGET_THRESHOLD_EXCEEDED,
    STALE_APPROVAL_ESCALATION,
    SUBACCOUNT_INVITED
}
