export const CATALOG_COPY = {
  picker: {
    title: 'Internal Product & Service Catalog',
    subtitle: 'Select pre-approved contracted items to auto-fill your requisition instantly.',
    searchPlaceholder: 'Search item name, code, description, category, or supplier...',
    allCategories: 'All Categories',
    preferredBadge: 'Preferred',
    contractBadge: 'Contracted',
    selectButton: 'Select & Auto-fill',
    noResults: 'No approved catalog items matching your criteria were found.',
    noResultsSub: 'If making a custom or spot purchase, you can continue filling the request manually.',
    unitPriceLabel: 'Unit Price',
    vatLabel: 'VAT',
    vendorLabel: 'Supplier',
    categoryLabel: 'Category',
    contractRefLabel: 'Contract Ref',
    validUntilLabel: 'Validity',
    autofillSuccess: 'Item details successfully populated to requisition line.',
  },
  admin: {
    pageTitle: 'Item Master & Enterprise Catalog',
    pageSubtitle: 'Manage corporate approved items, contracted unit prices, category taxonomy, and supplier alignments.',
    btnNewItem: 'New Catalog Item',
    btnManageCategories: 'Categories',
    btnImport: 'Import CSV',
    btnExport: 'Export CSV',
    health: {
      totalItems: 'Total Active Items',
      totalItemsSub: 'Selectable items in catalog',
      categories: 'Category Taxonomy',
      categoriesSub: 'Defined product categories',
      expiring30: 'Expiring Soon (<30 Days)',
      expiring30Sub: 'Renewal action required',
      expired: 'Expired Items',
      expiredSub: 'Automatically deactivated',
      preferredCount: 'Preferred Items',
    },
    table: {
      colCode: 'Item Code',
      colName: 'Item Name & Description',
      colCategory: 'Category',
      colVendor: 'Supplier',
      colPrice: 'Unit Price',
      colUom: 'UOM & VAT',
      colContract: 'Contract Status',
      colActions: 'Actions',
      empty: 'No catalog items registered yet.',
      emptyAction: 'Add your first item or bulk import via CSV.',
      activeStatus: 'Active',
      inactiveStatus: 'Inactive',
      deleteConfirmTitle: 'Deactivate Item',
      deleteConfirmMessage: 'Are you sure you want to deactivate this item? Historical purchase records will remain intact.',
    },
    drawer: {
      createTitle: 'Add New Catalog Item',
      editTitle: 'Edit Catalog Item',
      sectionBasic: 'Basic Information',
      sectionPricing: 'Pricing & Tax',
      sectionContract: 'Contract & Supplier',
      codeLabel: 'Item Code (Optional)',
      codePlaceholder: 'e.g. IT-LAP-001 (Auto-generated if empty)',
      nameLabel: 'Item Name',
      namePlaceholder: 'e.g. Dell Latitude 5540 15.6" Laptop',
      descLabel: 'Technical Description / Specs',
      descPlaceholder: 'RAM, SSD, model details, or service specifications...',
      categoryLabel: 'Category',
      categoryPlaceholder: 'Select category...',
      vendorLabel: 'Preferred Supplier',
      vendorPlaceholder: 'Select supplier...',
      priceLabel: 'Contracted Unit Price',
      currencyLabel: 'Currency',
      vatLabel: 'VAT Rate (%)',
      uomLabel: 'Unit of Measure',
      contractRefLabel: 'Contract Reference Number',
      contractRefPlaceholder: 'e.g. SZL-2026-DELL-01',
      validFromLabel: 'Contract Valid From',
      validUntilLabel: 'Contract Valid Until',
      preferredCheckbox: 'Mark as "Preferred" in its category',
      activeCheckbox: 'Active (Visible to employees in catalog)',
      glAccountLabel: 'General Ledger Account Code',
      glAccountPlaceholder: 'e.g. 760.01.001',
      saveSuccess: 'Catalog item saved successfully.',
      updateSuccess: 'Catalog item updated successfully.',
      deleteSuccess: 'Catalog item deactivated successfully.',
    },
    importModal: {
      title: 'Bulk Item Import (CSV)',
      subtitle: 'Upload product list supplied by vendors or exported from ERP in CSV format.',
      dragDropTitle: 'Drag & Drop CSV File or Browse',
      dragDropSub: 'Supports UTF-8 encoded .csv files up to 5MB',
      downloadTemplate: 'Download Sample CSV Template',
      processing: 'Processing CSV file...',
      successSummary: 'Successfully processed items:',
      errorSummary: 'Rows with errors:',
      colRow: 'Row',
      colItem: 'Item / Code',
      colError: 'Error Reason',
      uploadCTA: 'Upload & Import File',
    },
    categoryModal: {
      title: 'Category Taxonomy Management',
      subtitle: 'Create and organize hierarchical categories to group catalog items.',
      parentLabel: 'Parent Category (Optional)',
      parentPlaceholder: 'Root Category (Top level)',
      nameLabel: 'Category Name',
      namePlaceholder: 'e.g. Monitors & Displays',
      codeLabel: 'Category Code',
      codePlaceholder: 'e.g. CAT-IT-MON',
      iconLabel: 'Icon Code',
      descLabel: 'Description',
      createSuccess: 'Category created successfully.',
    },
  },
} as const
