/**
 * All copy and label constants for the Purchasing (PO & Vendor) module.
 * Zero hardcode policy — everything is defined here in English.
 */
export const PURCHASING_COPY = {
  orders: {
    pageTitle:          'Purchase Orders',
    pageSubtitle:       'Issue, track, and manage commercial purchase orders and supplier contracts.',
    createCTA:          '+ Create Purchase Order',
    vendorsCTA:         'Vendor Master Directory',
    searchPlaceholder:  'Search by PO number, vendor, or PR reference...',
    filterStatus:       'All Statuses',
    filterVendor:       'All Vendors',
    colPoNumber:        'PO Number',
    colVendor:          'Vendor & Tax ID',
    colCostCenter:      'Cost Center',
    colIncoterms:       'Incoterms / Terms',
    colAmount:          'Total Amount',
    colStatus:          'Status',
    colDate:            'Issued Date',
    colActions:         'Actions',
    issueAction:        'Issue to Vendor',
    inspectAction:      'Inspect',
    reviseAction:       'Revise PO',
    cancelAction:       'Cancel PO',
    emptyTitle:         'No Purchase Orders Found',
    emptyDesc:          'No purchase orders match your filter criteria. Create a new purchase order or convert an approved PR.',
  },
  create: {
    pageTitle:          'Create Purchase Order',
    pageSubtitle:       'Generate a formal commercial order for supplier procurement.',
    backToList:         'Back to Purchase Orders',
    tabConvertPR:       'Convert Approved PR',
    tabDirectPO:        'Direct Standalone PO',
    selectPRLabel:      'Select Approved Purchase Requisition',
    selectPRPlaceholder:'Choose an approved requisition to auto-fill details...',
    sectionHeader:      '1. Commercial & Entity Scope',
    sectionTerms:       '2. Delivery & Incoterms 2020',
    sectionItems:       '3. Order Line Items Breakdown',
    legalEntityLabel:   'Legal Entity',
    costCenterLabel:    'Cost Center',
    facilityLabel:      'Delivery Facility',
    vendorLabel:        'Supplier / Vendor',
    vendorPlaceholder:  'Select approved vendor...',
    incotermsLabel:     'Incoterms 2020',
    paymentTermsLabel:  'Payment Terms',
    currencyLabel:      'Currency',
    notesLabel:         'Special Instructions / Order Notes',
    notesPlaceholder:   'Enter delivery instructions, dock receiving hours, or contract references...',
    addLineCTA:         '+ Add Line Item',
    cancelButton:       'Discard',
    saveDraftCTA:       'Create Purchase Order (Draft)',
    savingStatus:       'Creating Purchase Order...',
  },
  vendors: {
    pageTitle:          'Vendor Master Directory',
    pageSubtitle:       'Manage approved enterprise suppliers, tax profiles, and compliance ratings.',
    backToOrders:       'Back to Purchase Orders',
    onboardCTA:         '+ Onboard New Vendor',
    searchPlaceholder:  'Search by vendor name, tax number (VKN), or city...',
    filterCategory:     'All Categories',
    filterStatus:       'All Statuses',
    colName:            'Vendor Name & VKN',
    colCategory:        'Category',
    colTier:            'Supplier Tier',
    colEInvoice:        'e-Invoice (GİB)',
    colPaymentTerms:    'Payment Terms',
    colBank:            'Bank & IBAN',
    colStatus:          'Status',
    colActions:         'Actions',
    emptyTitle:         'No Vendors Found',
    emptyDesc:          'No suppliers match your filter criteria. Click Onboard New Vendor to register a supplier.',
  },
  onboardModal: {
    title:              'Onboard New Enterprise Vendor',
    desc:               'Register a new commercial supplier with corporate tax identity, banking credentials, and default commercial terms.',
    nameLabel:          'Vendor Legal Name',
    taxNumberLabel:     'Tax Number (VKN / VAT)',
    taxOfficeLabel:     'Tax Office',
    categoryLabel:      'Vendor Category',
    tierLabel:          'Supplier Tier',
    eInvoiceLabel:      'e-Invoice Registered (GİB Mükellefi)',
    orderEmailLabel:    'Official Order Email',
    phoneLabel:         'Phone Number',
    addressLabel:       'Registered Address',
    cityLabel:          'City',
    countryLabel:       'Country',
    paymentTermsLabel:  'Default Payment Terms',
    bankNameLabel:      'Bank Name',
    ibanLabel:          'IBAN',
    cancelCTA:          'Cancel',
    submitCTA:          'Register Vendor',
    submitting:         'Registering Supplier...',
  },
  drawer: {
    title:              'Purchase Order Details',
    subtitle:           'Inspect commercial terms, delivery facility, and line items.',
    sectionVendor:      'Supplier Commercial Profile',
    sectionScope:       'Order Context & Delivery',
    sectionItems:       'Ordered Line Items',
    sectionRevisions:   'PO Revision Audit Trail',
    issuedTo:           'Issued To:',
    taxNumber:          'Tax Number (VKN):',
    orderEmail:         'Order Email:',
    incoterms:          'Incoterms:',
    paymentTerms:       'Payment Terms:',
    destination:        'Delivery Destination:',
    notes:              'Order Notes:',
    noRevisions:        'Original Order (Revision 0). No revisions have been issued.',
  },
  modals: {
    issueTitle:         'Issue Purchase Order to Vendor',
    issueDesc:          'Issuing this PO will transition the order to ISSUED and dispatch the commercial order payload to the vendor email. Are you sure you want to proceed?',
    cancelTitle:        'Cancel Purchase Order',
    cancelDesc:         'Cancelling this PO will terminate the commercial order. Please provide a mandatory reason for cancellation.',
    cancelReasonLabel:  'Cancellation Reason (Required)',
    cancelReasonPlaceholder: 'Explain the business rationale for canceling this order...',
    cancelReasonMinError:'Cancellation reason must be at least 5 characters.',
  },
  incotermsOptions: [
    { value: 'DAP', label: 'DAP - Delivered at Place (Standard)' },
    { value: 'DDP', label: 'DDP - Delivered Duty Paid (Import)' },
    { value: 'EXW', label: 'EXW - Ex Works (Pickup)' },
    { value: 'FOB', label: 'FOB - Free on Board' },
    { value: 'CIF', label: 'CIF - Cost, Insurance and Freight' },
    { value: 'CPT', label: 'CPT - Carriage Paid To' },
  ],
  paymentTermsOptions: [
    { value: 'NET_30', label: 'Net 30 Days (Standard)' },
    { value: 'NET_15', label: 'Net 15 Days' },
    { value: 'NET_45', label: 'Net 45 Days' },
    { value: 'NET_60', label: 'Net 60 Days' },
    { value: 'NET_90', label: 'Net 90 Days' },
    { value: 'IMMEDIATE', label: 'Immediate / Cash' },
    { value: 'CASH_IN_ADVANCE', label: 'Cash in Advance / Prepayment' },
  ],
  categoryOptions: [
    { value: 'SOFTWARE_SAAS', label: 'Software & Cloud SaaS Licenses' },
    { value: 'IT_HARDWARE', label: 'IT Hardware & Workstations' },
    { value: 'CONSULTING_PROFESSIONAL', label: 'Consulting & Professional Services' },
    { value: 'OFFICE_SUPPLIES', label: 'Office Supplies & Equipment' },
    { value: 'FACILITY_SERVICES', label: 'Facility Maintenance & Services' },
    { value: 'LOGISTICS_TRANSPORT', label: 'Logistics & Freight Transport' },
  ],
  tierOptions: [
    { value: 'TIER_1_STRATEGIC', label: 'Tier 1 - Strategic Key Partner' },
    { value: 'TIER_2_PREFERRED', label: 'Tier 2 - Preferred Supplier' },
    { value: 'TIER_3_STANDARD', label: 'Tier 3 - Standard / Spot Supplier' },
  ],
} as const
