package com.enterprise.spendsync.catalog.service;

import com.enterprise.spendsync.catalog.dto.CatalogCategoryCreateRequest;
import com.enterprise.spendsync.catalog.dto.CatalogCategoryDto;
import com.enterprise.spendsync.catalog.dto.CatalogItemCreateRequest;
import com.enterprise.spendsync.catalog.dto.CatalogItemResponse;
import com.enterprise.spendsync.catalog.dto.CatalogItemUpdateRequest;
import com.enterprise.spendsync.catalog.dto.CsvImportResultDto;
import com.enterprise.spendsync.catalog.internal.domain.CatalogCategory;
import com.enterprise.spendsync.catalog.internal.domain.CatalogItem;
import com.enterprise.spendsync.catalog.internal.repository.CatalogCategoryRepository;
import com.enterprise.spendsync.catalog.internal.repository.CatalogItemRepository;
import com.enterprise.spendsync.catalog.internal.service.CatalogAdminServiceImpl;
import com.enterprise.spendsync.core.internal.domain.Tenant;
import com.enterprise.spendsync.core.internal.domain.User;
import com.enterprise.spendsync.core.internal.repository.TenantRepository;
import com.enterprise.spendsync.purchasing.internal.domain.PaymentTerms;
import com.enterprise.spendsync.purchasing.internal.domain.Vendor;
import com.enterprise.spendsync.purchasing.internal.domain.VendorCategory;
import com.enterprise.spendsync.purchasing.internal.domain.VendorTier;
import com.enterprise.spendsync.purchasing.internal.repository.VendorRepository;
import com.enterprise.spendsync.shared.exception.ResourceNotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.ByteArrayInputStream;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class CatalogAdminServiceBranchTest {

    @Mock private CatalogItemRepository itemRepository;
    @Mock private CatalogCategoryRepository categoryRepository;
    @Mock private VendorRepository vendorRepository;
    @Mock private TenantRepository tenantRepository;

    @InjectMocks
    private CatalogAdminServiceImpl catalogAdminService;

    private UUID tenantId;
    private Tenant tenant;
    private User adminUser;
    private CatalogCategory category;
    private Vendor vendor;

    @BeforeEach
    void setUp() {
        tenantId = UUID.randomUUID();
        tenant = new Tenant("Catalog Tenant", "cat-tenant");
        tenant.setId(tenantId);

        adminUser = new User("admin@test.com", "hash", "Admin", "User", null, "TR");
        adminUser.setId(UUID.randomUUID());

        category = new CatalogCategory(tenant, null, "CAT-IT", "IT Equipment", null, null);
        category.setId(UUID.randomUUID());
        category.setFullPath("IT Equipment");

        vendor = new Vendor(tenant, "Tech Corp", "1112223334", "Istanbul", VendorCategory.IT_HARDWARE,
                VendorTier.TIER_1_STRATEGIC, true, "tech@corp.com", "555-0000",
                "Address", "Istanbul", "TR", PaymentTerms.NET_30, "Garanti", "TR000000");
        vendor.setId(UUID.randomUUID());
    }

    @Test
    @DisplayName("Should auto-generate item code and compute contract alert categories")
    void shouldCreateItemWithAutoGeneratedCodeAndAlerts() {
        CatalogItemCreateRequest request = new CatalogItemCreateRequest(
                null, "Ultra Laptop 15", "Top spec", category.getId(), vendor.getId(),
                new BigDecimal("25000.00"), "TRY", new BigDecimal("0.20"), "UNIT", "CTR-01",
                LocalDate.now().minusDays(10), LocalDate.now().plusDays(5), true, "GL-100");

        when(tenantRepository.findById(tenantId)).thenReturn(Optional.of(tenant));
        when(categoryRepository.findByTenantIdAndId(tenantId, category.getId())).thenReturn(Optional.of(category));
        when(vendorRepository.findByIdAndTenantId(vendor.getId(), tenantId)).thenReturn(Optional.of(vendor));
        when(itemRepository.save(any(CatalogItem.class))).thenAnswer(i -> {
            CatalogItem itm = i.getArgument(0);
            itm.setId(UUID.randomUUID());
            return itm;
        });

        CatalogItemResponse response = catalogAdminService.createCatalogItem(tenantId, request, adminUser);

        assertThat(response).isNotNull();
        assertThat(response.itemCode()).contains("ULTRA-LAPTOP-15");
        assertThat(response.contractAlert()).contains("CRITICAL CONTRACT EXPIRY");
    }

    @Test
    @DisplayName("Should compute contract expired alert when validUntil is in the past")
    void shouldComputeExpiredContractAlert() {
        CatalogItemCreateRequest request = new CatalogItemCreateRequest(
                "CODE-EXP", "Expired Product", "Desc", null, null,
                new BigDecimal("100.00"), "TRY", new BigDecimal("0.20"), "EA", null,
                LocalDate.now().minusMonths(6), LocalDate.now().minusDays(1), false, null);

        when(tenantRepository.findById(tenantId)).thenReturn(Optional.of(tenant));
        when(itemRepository.findByTenantIdAndItemCode(tenantId, "CODE-EXP")).thenReturn(Optional.empty());
        when(itemRepository.save(any(CatalogItem.class))).thenAnswer(i -> {
            CatalogItem itm = i.getArgument(0);
            itm.setId(UUID.randomUUID());
            return itm;
        });

        CatalogItemResponse response = catalogAdminService.createCatalogItem(tenantId, request, adminUser);

        assertThat(response.contractAlert()).contains("CONTRACT EXPIRED");
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException for invalid category or vendor on create")
    void shouldThrowWhenCategoryOrVendorNotFoundOnCreate() {
        CatalogItemCreateRequest requestCat = new CatalogItemCreateRequest(
                "C1", "P1", "D", UUID.randomUUID(), null, new BigDecimal("10"), "TRY",
                new BigDecimal("0.20"), "EA", null, null, null, false, null);

        when(tenantRepository.findById(tenantId)).thenReturn(Optional.of(tenant));
        when(itemRepository.findByTenantIdAndItemCode(eq(tenantId), any())).thenReturn(Optional.empty());
        when(categoryRepository.findByTenantIdAndId(eq(tenantId), any())).thenReturn(Optional.empty());

        assertThatThrownBy(() -> catalogAdminService.createCatalogItem(tenantId, requestCat, adminUser))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("Category not found");

        CatalogItemCreateRequest requestVen = new CatalogItemCreateRequest(
                "C2", "P2", "D", null, UUID.randomUUID(), new BigDecimal("10"), "TRY",
                new BigDecimal("0.20"), "EA", null, null, null, false, null);

        when(vendorRepository.findByIdAndTenantId(any(), eq(tenantId))).thenReturn(Optional.empty());

        assertThatThrownBy(() -> catalogAdminService.createCatalogItem(tenantId, requestVen, adminUser))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("Vendor not found");
    }

    @Test
    @DisplayName("Should clear category and vendor on update when null IDs passed")
    void shouldClearCategoryAndVendorOnUpdate() {
        UUID itemId = UUID.randomUUID();
        CatalogItem item = new CatalogItem(tenant, "ITEM-1", "Name", "Desc", category, vendor,
                new BigDecimal("100.00"), "TRY", new BigDecimal("0.20"), "EA", null, null, null, false, null, null);
        item.setId(itemId);

        when(itemRepository.findByTenantIdAndId(tenantId, itemId)).thenReturn(Optional.of(item));
        when(itemRepository.save(any(CatalogItem.class))).thenAnswer(i -> i.getArgument(0));

        CatalogItemUpdateRequest updateRequest = new CatalogItemUpdateRequest(
                "New Name", "New Desc", null, null, new BigDecimal("120.00"),
                "USD", new BigDecimal("0.18"), "BOX", "CTR-NEW", LocalDate.now(),
                LocalDate.now().plusMonths(6), true, true, "GL-200");

        CatalogItemResponse response = catalogAdminService.updateCatalogItem(tenantId, itemId, updateRequest);

        assertThat(response.categoryName()).isNull();
        assertThat(response.preferredVendorName()).isNull();
        assertThat(response.currency()).isEqualTo("USD");
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException when item not found on update or delete")
    void shouldThrowWhenItemNotFoundOnUpdateOrDelete() {
        UUID randomId = UUID.randomUUID();
        when(itemRepository.findByTenantIdAndId(tenantId, randomId)).thenReturn(Optional.empty());

        CatalogItemUpdateRequest updateRequest = new CatalogItemUpdateRequest(
                "Name", "Desc", null, null, BigDecimal.TEN, "TRY", null, null, null, null, null, null, null, null);

        assertThatThrownBy(() -> catalogAdminService.updateCatalogItem(tenantId, randomId, updateRequest))
                .isInstanceOf(ResourceNotFoundException.class);

        assertThatThrownBy(() -> catalogAdminService.deleteCatalogItem(tenantId, randomId))
                .isInstanceOf(ResourceNotFoundException.class);
    }

    @Test
    @DisplayName("Should handle CSV import errors for empty file, bad columns, bad price, and blank name")
    void shouldHandleCsvImportValidationErrors() {
        when(tenantRepository.findById(tenantId)).thenReturn(Optional.of(tenant));

        // Empty file
        CsvImportResultDto emptyResult = catalogAdminService.importCatalogFromCsv(
                tenantId, new ByteArrayInputStream(new byte[0]), adminUser);
        assertThat(emptyResult.errors()).hasSize(1);
        assertThat(emptyResult.errors().get(0).errorMessage()).contains("empty");

        // Invalid columns and bad price
        String invalidCsv = "header\n" +
                "COL1,COL2\n" + // < 6 columns
                "CODE, ,Desc,Cat,Ven,100\n" + // blank name
                "CODE2,Name,Desc,Cat,Ven,INVALID_PRICE\n"; // bad price

        CsvImportResultDto errorResult = catalogAdminService.importCatalogFromCsv(
                tenantId, new ByteArrayInputStream(invalidCsv.getBytes(StandardCharsets.UTF_8)), adminUser);
        assertThat(errorResult.failureCount()).isEqualTo(3);
    }

    @Test
    @DisplayName("Should export catalog items to CSV format")
    void shouldExportCatalogToCsv() {
        CatalogItem item = new CatalogItem(tenant, "EXP-01", "Export Item", "Description with \"quotes\"",
                category, vendor, new BigDecimal("500.00"), "TRY", new BigDecimal("0.20"), "EA", "CTR-99",
                LocalDate.of(2026, 1, 1), LocalDate.of(2026, 12, 31), true, null, null);

        when(itemRepository.findByTenantId(tenantId)).thenReturn(List.of(item));

        byte[] csvBytes = catalogAdminService.exportCatalogToCsv(tenantId);
        String csv = new String(csvBytes, StandardCharsets.UTF_8);

        assertThat(csv).contains("item_code,name,description");
        assertThat(csv).contains("EXP-01");
        assertThat(csv).contains("Export Item");
        assertThat(csv).contains("Tech Corp");
    }
}
