export const RECEIVING_COPY = {
  header: {
    title: 'Goods Receipt & Dock Inspection',
    subtitle: 'Inspect physical inbound shipments, verify waybills, and log damage quarantines.',
    newReceivingCTA: '+ Process Dock Receipt',
    viewHistoryCTA: 'Receiving History',
  },
  kpi: {
    pendingDeliveries: 'Pending Dock Shipments',
    pendingDesc: 'Active vendor orders in transit',
    totalProcessed: 'Waybills Processed',
    totalDesc: 'Officially received at receiving docks',
    quarantined: 'Discrepancy / Damage Holds',
    quarantinedDesc: 'Partial rejections logged',
  },
  table: {
    colPoNumber: 'Purchase Order #',
    colVendor: 'Supplier',
    colFacility: 'Delivery Dock',
    colItems: 'Items Count',
    colAmount: 'PO Value',
    colTerms: 'Incoterms',
    colIssued: 'Issued Date',
    colStatus: 'Order Status',
    colActions: 'Action',
    receiveAction: 'Receive at Dock',
    searchPlaceholder: 'Search PO number, supplier, or dock facility...',
    emptyTitle: 'No Pending Shipments at Dock',
    emptyDesc: 'All issued purchase orders have been processed and received.',
  },
  create: {
    pageTitle: 'Dock Goods Receipt & Inspection',
    pageSubtitle: 'Verify supplier delivery note / waybill and record accepted vs rejected quantities.',
    backToList: 'Back to Pending Deliveries',
    poSelectSection: '1. Inbound Shipment Identification',
    poSelectLabel: 'Select Inbound Purchase Order',
    poSelectPlaceholder: 'Select an issued order awaiting delivery...',
    waybillSection: '2. Waybill & Dispatch Documentation',
    waybillNumberLabel: 'Waybill / Delivery Note #',
    waybillNumberPlaceholder: 'e.g. WB-2026-98124',
    waybillDateLabel: 'Waybill Date',
    facilityLabel: 'Receiving Dock Facility',
    notesLabel: 'Receiving Officer Notes / Seal Status',
    notesPlaceholder: 'Enter dock inspection remarks, package integrity, seal numbers...',
    inspectionSection: '3. Physical Line Inspection & Acceptance',
    submitCTA: 'Submit Goods Receipt (GR)',
    submittingCTA: 'Processing Dock Inspection...',
  },
  inspectionTable: {
    colLine: '#',
    colDescription: 'Item Description',
    colOrdered: 'Ordered Qty',
    colReceived: 'Received Qty',
    colAccepted: 'Accepted Qty',
    colRejected: 'Damaged / Rejected',
    colRejectionReason: 'Rejection Reason',
    colNotes: 'Inspection Remarks',
    toleranceNotice: 'Over-delivery tolerance: Max allowed is',
  },
  drawer: {
    title: 'Goods Receipt Inspection Voucher',
    subtitle: 'Dock inspection record and line-item acceptance details.',
    waybill: 'Waybill / Delivery Note:',
    receivedBy: 'Received By:',
    receivedAt: 'Inspection Date:',
    sectionItems: 'Itemized Receiving & Acceptance Breakdown',
    acceptedSummary: 'Accepted for Inventory / AP Matching',
    rejectedSummary: 'Quarantined / Returned to Supplier',
  },
  history: {
    title: 'Goods Receipt Inspection Archive',
    subtitle: 'Permanent log of all physical dock inspections and accepted waybills.',
    colGrNumber: 'Receipt # (GR)',
    colPoNumber: 'PO Reference',
    colWaybill: 'Waybill #',
    colVendor: 'Supplier',
    colFacility: 'Receiving Dock',
    colReceivedBy: 'Inspector',
    colDate: 'Receipt Date',
    colStatus: 'Status',
    backToQueue: 'Back to Dock Receiving',
  },
} as const
