name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Backend Unit Test Suite
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute Backend Unit Tests
        working-directory: ./backend
        run: mvn test -Dtest="!*ContainerTest"
