/**
 * All copy and label constants for the Approval Queue & Manager Workbench.
 * Zero hardcode policy — everything is defined here in English.
 */
export const APPROVAL_COPY = {
  queue: {
    pageTitle:          'Approval Workbench',
    pageSubtitle:       'Review, evaluate, and sign off purchase requisitions within your authority threshold.',
    refreshCTA:         'Refresh Queue',
    searchPlaceholder:  'Search by PR number, title, or requester...',
    filterCostCenter:   'All Cost Centers',
    colPrNumber:        'PR Number',
    colTitle:           'Title / Justification',
    colCostCenter:      'Cost Center',
    colRequester:       'Requester',
    colLevel:           'Approval Step',
    colAmount:          'Total Estimated Amount',
    colAge:             'Waiting Time',
    colActions:         'Decisions',
    quickApprove:       'Approve',
    quickReject:        'Reject',
    inspect:            'Inspect',
    emptyTitle:         'No Approvals Pending',
    emptyDesc:          'Your approval queue is completely clear. All purchase requisitions have been processed.',
  },
  metrics: {
    pendingCount:       'Pending Approvals',
    pendingDesc:        'Requests awaiting your signature',
    totalExposure:      'Total Queue Exposure',
    exposureDesc:       'Cumulative estimated spend',
    authorizedLimit:    'Your Signing Limit',
    unlimitedLimit:     'Unlimited Authority (CFO / Board)',
    thresholdLabel:     'Up to',
    urgentSLA:          'Action Overdue (> 3 Days)',
    urgentDesc:         'Requires immediate executive attention',
  },
  modals: {
    approveTitle:       'Approve Purchase Requisition',
    approveDesc:        'You are signing off on this requisition. Reserved budget allocations will remain locked and the request will advance to the next workflow stage.',
    decisionNoteLabel:  'Decision Note (Optional)',
    decisionNotePlaceholder: 'Add any conditions, remarks, or cost allocation guidance...',
    confirmApproveCTA:  'Confirm Approval',
    approvingStatus:    'Submitting Decision...',

    rejectTitle:        'Reject Purchase Requisition',
    rejectDesc:         'Rejecting this requisition will cancel all pending approval steps and immediately release reserved funds back to the cost center.',
    rejectionReasonLabel: 'Rejection Reason (Required)',
    rejectionReasonPlaceholder: 'Provide specific rationale (e.g. over-budget, preferred alternative supplier, or duplicate request)...',
    rejectionReasonMinError: 'Rejection reason must be at least 5 characters.',
    confirmRejectCTA:   'Confirm Rejection',
    rejectingStatus:    'Processing Rejection...',
  },
  drawer: {
    title:              'Requisition Inspection',
    subtitle:           'Review line items, delivery location, and cost center budget impact before deciding.',
    sectionOverview:    'Request Scope',
    sectionItems:       'Line Items Breakdown',
    sectionBudget:      'Cost Center Budget Impact',
    sectionTimeline:    'Approval Chain Timeline',
    btnApprove:         'Approve Requisition',
    btnReject:          'Reject Requisition',
  },
  bulk: {
    selectedCount:      'requisitions selected',
    totalValue:         'Total Value:',
    bulkApproveCTA:     'Approve Selected',
    clearSelection:     'Clear Selection',
    confirmBulkTitle:   'Bulk Approve Requisitions',
    confirmBulkDesc:    'Are you sure you want to batch-approve these selected requisitions? All items will advance simultaneously.',
  },
  warnings: {
    sodViolation:       'Segregation of Duties Warning: You submitted this requisition. Self-approval is strictly forbidden.',
    limitExceeded:      'Warning: This requisition amount exceeds your authorized signing limit. Approval will require higher escalation.',
  },
} as const
